name: livevideo

services:
  django:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: django
    container_name: django
    ports:
      - 8080:8080
    env_file:
      - .env
    environment:
      - PYTHONPATH=/usr/src/app/livevideo
    networks:
      - livevideo
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - postgres
    # restart: unless-stopped

  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: react
    container_name: react
    ports:
      - 5173:5000
    env_file:
      - .env
    # environment:
    #   - CHOKIDAR_USEPOLLING=true
    # tty: true
    networks:
      - livevideo
    volumes:
      - ./frontend:/app
      - /app/node_modules # to avoid overwriting node_modules
    depends_on:
      - django

  postgres:
    image: postgres:16.4-alpine3.20
    container_name: postgres
    env_file:
      - .env
    environment:
      LC_COLLATE: en_US.UTF-8
      LC_CTYPE: en_US.UTF-8
    expose:
      - 5432
    working_dir: /var/lib/postgresql/data
    networks:
      - livevideo
    volumes:
      - postgres_database:/var/lib/postgresql/data
    restart: unless-stopped


volumes:
  # frontend:
  #   name: frontend
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ./frontend/
  # backend:
  #   name: backend
  #   driver: local
  #   driver_opts:
  #     type: none
  #     o: bind
  #     device: ./backend/
  postgres_database:
    name: postgres_database
    driver: local


networks:
  livevideo:
    name: livevideo
    driver: bridge
