# Generated by Django 5.2 on 2025-04-11 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livevideo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectionlog',
            options={'verbose_name': 'Established Connection Log', 'verbose_name_plural': 'Established Connection Logs'},
        ),
    ]
